#pragma once

#ifndef FLY_DEBUG
#define FLY_DEBUG 1
#endif // !FLY_DEBUG

#ifndef ENABLE_MEM_PROFILER
#define ENABLE_MEM_PROFILER FLY_DEBUG
#endif // !ENABLE_MEM_PROFILER

#ifndef ENABLE_ASSERTIONS
#define ENABLE_ASSERTIONS FLY_DEBUG
#endif // !ENABLE_ASSERTIONS

#ifdef PLATFORM_64BITS
#define PLATFORM_32BITS 1
#endif // PLATFORM_64BITS

#ifdef PLATFORM_32BITS
#define PLATFORM_64BITS 1
#endif // PLATFORM_32BITS


